name: Deploy to WordPress.org
on:
  release:
    types: [released]
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master

            - name: Install dependencies
              run: npm install

            - name: Build plugin zip
              run: npm run plugin-zip

            - name: Deploy to WordPress.org
              uses: 10up/action-wordpress-plugin-deploy@stable
              with:
                  generate-zip: false
                  dry-run: true
              env:
                  SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
                  SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
                  SLUG: todo-list-block
